cmake_minimum_required(VERSION 3.16)
project(ConfiguratorModel  VERSION 1.1.1 LANGUAGES CXX)
include("${CMAKE_CURRENT_SOURCE_DIR}/../../../tools/workspace.cmake")
create_target(model)

find_package(Boost 1.8 REQUIRED COMPONENTS json system)
target_link_libraries(ConfiguratorModel PRIVATE Boost::json Boost::system)